a_view_for_you/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('auth/', include('authentication.urls')),
    path('landscape/', include('landscape.urls')),
] 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

landscape/urls.py
from django.urls import path
from landscape import views

app_name = 'landscape'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('<slug:landscape_name_slug>/', views.show_landscape, name='show_landscape'),
    path('<slug:landscape_name_slug>/add_review/', views.add_review, name='add_review'),
    path('<slug:landscape_name_slug>/like', views.add_like, name='add_like'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.show_profile, name='profile'),
    path('edit/', views.edit_profile, name='edit'),
]

profiles/views.py
from django.shortcuts import redirect, render
from landscape.models import saved_landscapes, Review
from django.contrib.auth.decorators import login_required
from profiles.form import ProfileForm

@login_required()
def show_profile(request):
    context_dict = {}
    if request.method == 'GET':
        context_dict = {}
        profile_likes = set()
        try:
            profile_saved_landscapes = saved_landscapes.objects.filter(
                user_id=request.user.id).select_related('landscape_id')
            for like in profile_saved_landscapes:
                # like.landscape_id is not a integer but a Landscape instance!
                profile_likes.add(like.landscape_id)
            #profile_likes is a set of landscapes
            context_dict['profile_likes'] = profile_likes
        except saved_landscapes.DoesNotExist:
            # do nothing
            context_dict['profile_likes'] = None

        try:
            profile_reviews = Review.objects.filter(
                user_id=request.user.id).order_by('-visit_date')
            context_dict['profile_reviews'] = profile_reviews
        except Review.DoesNotExist:
            # do nothing
            context_dict['profile_reviews'] = None

    return render(request, 'profile/profile.html', context=context_dict)
    #return render(request, 'profile/profile.html')

# try to filter users who likes this landscape
def show_landscape_likes(request):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    landscape_likes = set()
    try:
        saved_landscape_likes = saved_landscapes.objects.filter(
            landscpae_id=request.landscape.id)
        for like in saved_landscape_likes:
            #like.user_id is not a integer but a user instance!
            landscape_likes.add(like.user_id)
        #landscape_likes is a set of users
        context_dict['landscape_likes'] = landscape_likes
    except saved_landscapes.DoesNotExist:
        # do nothing
        context_dict['landscape_likes'] = None
    return render(request, 'profile/profile.html', context=context_dict)

# try to filter users who reviewed this landscape
def show_landscape_reviews(request):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    landscape_review = set()
    try:
        saved_landscape_reviews = Review.objects.filter(
            landscpae_id=request.landscape.id)
        for review in saved_landscape_reviews:
            #like.user_id is not a integer but a user instance!
            landscape_review.add(review.user_id)
        #landscape_reviews is a set of users
        context_dict['landscape_review'] = landscape_review
    except saved_landscapes.DoesNotExist:
        # do nothing
        context_dict['landscape_review'] = None
    return render(request, 'profile/profile.html', context=context_dict)

@login_required()
def edit_profile(request):
    profileForm = {}
    if request.method == 'GET':
        profileForm = ProfileForm()
    if request.method == 'POST':
        profileForm = ProfileForm(request.POST)
        if profileForm.is_valid():
            if 'profile_image' in request.FILES:
                request.user.profile_image = request.FILES['profile_image']
                #request.user.introduction = "changed"
            if not request.POST['introduction'] is None:
                request.user.introduction = request.POST['introduction']
            request.user.save()
            return redirect("profile:profile")
    return render(request, 'profile/edit_profile.html', {'form': profileForm})

templates/profile/edit_profile.html
{% extends 'base.html' %}
{% load static %}


{% block script_block %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block title_block %}
Edit profile
{% endblock %}


{% block body_block %}
<h3>Edit profile</h3>
<form action="{%url 'profile:edit'%}" method = 'POST' enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <fieldset class="form-group register-form">
        <label class="control-label" for="id_{{ field.name }}">{{ field.label }}</label>
        {{ field }}
        {% if field.errors %}
            <span class="error-message">{{ field.errors.0 }}</span>
        {% endif %}
        <span></span>
    </fieldset>
    {% endfor %}
    <center><input type="submit" value="Update" class = 'btn btn-primary button'></center>
</form>
{% endblock %}

templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}

{% block script_block %}
    <link rel="stylesheet" href="{% static 'css/profile.css'%}">
    <script src = "{% static 'js/homepage.js'%}"></script>
{% endblock %}

{% block body_block %}
    <!-- Profile widget -->
    <div class="row  mx-5 py-3">
        <!-- username and image-->
        <div class="bg-light px-4 cover">
            <div class="media  align-items-end profile-head justify-content-between">
                <div class="profile mr-3">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <img width="200px" src="{{ user.image_url|default_if_none:'https://cdn3.vectorstock.com/i/1000x1000/34/52/user-icon-male-person-symbol-profile-avatar-sign-vector-19413452.jpg' }}" alt="{{ user.username }}'s profile image" class="mb-3">
                        </li>
                        <li class="list-inline-item">
                            <p style="font-size: x-large; " class="mt-2 mb-0">{{ user.username|default:"Username" }}</p>
                            <p class="small" style="word-break:break-all; width:200px"> <i class="fas fa-map-marker-alt mr-2">{{ user.introduction|default:"Brief Introduction" }}</i></p>
                        </li>
                    </ul>
                    <a href="{% url 'profile:edit' %}" class="btn btn-outline-primary"  style=" width:200px "> <strong>EDIT</strong></a>
                </div>
            </div>
        </div>
        
        <!-- number of likes and reviews -->
        <div class="bg-light px-4 pt-0 pb-3 d-flex justify-content-end text-center">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <h5 class="font-weight-bold mb-0 d-block">❤{{profile_likes|length}}</h5>
                    <h5 class="text-muted"> <a href="#likes" class="fa fa-picture-o mr-1">Likes</a></h5>
                </li>
                <li class="list-inline-item">
                    <h5 class="font-weight-bold mb-0 d-block"><span size="10" style="font-size:125%; color:gold">★</span>{{profile_reviews|length}}</h5>
                    <h5 class="text-muted"> <a href="#reviews" class="fa fa-user-circle-o mr-1">Reviews</a></h5>
                </li>
            </ul>
        </div>
    </div>

    <div class="row mx-4 py-3">
        <!-- likes -->
        <div id="likes" class="d-flex align-items-center justify-content-between mb-3">
            <h5 class="mb-0">Favourites</h5>
        </div>
        {% if profile_likes %}
        <div class="row mx-3">
            <!-- list likes -->
            <div class="card-group"></div>
                {% for l in profile_likes %}
                    <div class="card mx-2 my-3">
                        <a class="landscape_url" href="{% url 'landscape:show_landscape' l.slug %}">
                            <img class="card-img-top" style="max-height: 12rem;" src="{{ l.image.url }}" alt="landscape-image">
                            <div class="card-body">
                                <div class="row">
                                    <h5 class="card-title">{{l.name}}</h5>
                                    <div class="col-9">
                                        <p class="rating"  value = '{{l.review.average_rating}}' style = 'display:inline;'></p>
                                        <p class="card-text">{{l.review_num}} reviews</p>
                                    </div>
                                    <div class="col-3">
                                        ❤<br>
                                        <p class="card-text">{{l.like_num}} likes</p>
                                    </div>
                                </div>
                            </div>  
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        {%else%}
            <!-- if no likes, show a template for testing -->
            <li><strong>You have no likes.</strong></li>
        {%endif%}
    </div>

    <div class="row mx-4 py-3">
    <!-- reviews -->
        <div id="reviews" class="d-flex align-items-center justify-content-between mb-3">
            <h5 class="mb-0">Recent reviews</h5>
        </div>
        <div class="row">
            <!-- list reviews -->
            {% if profile_reviews %}
                {% for r in profile_reviews %}
                    <div class='review-result-container' style="display:block">
                        <div class='review-result-container-content'>
                            <p>
                                You authored a review on
                                <a href="{% url 'landscape:show_landscape' r.landscape_id.slug %}">{{r.landscape_id}}</a>
                                <span style="float:right;">
                                    {{ r.visit_date|default:"Date" }}
                                </span>
                            </p>
                            <h4>{{ r.title|default:"Title" }}</h4>
                            <div class="review_row">
                                <div class="review_column">
                                    <div class="rating"  value = '{{r.rating}}' style = 'display:inline; padding: 2px;'></div>
                                </div>
                                <div class="review_column">
                                    <p>{{ r.description|default:"description" }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {%else%}
                <!-- if no reviews, show a template for testing -->
                <li><strong>You have no reviews.</strong></li>
            {%endif%}
        </div>
    </div>
{% endblock %}









    





 