a_view_for_you/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('auth/', include('authentication.urls')),
    path('landscape/', include('landscape.urls')),
] 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from .views import login, register, logout
from django.urls import path

app_name = 'auth'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout')
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

landscape/urls.py
from django.urls import path
from landscape import views

app_name = 'landscape'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('<slug:landscape_name_slug>/', views.show_landscape, name='show_landscape'),
    path('<slug:landscape_name_slug>/add_review/', views.add_review, name='add_review'),
    path('<slug:landscape_name_slug>/like', views.add_like, name='add_like'),
]

home/views.py
from django.shortcuts import render
import json
import urllib
from utils import utils


# Create your views here.

def homepage(request):
    if request.method == 'GET':
        location = request.COOKIES.get('location')
        if location:
            location = json.loads(urllib.parse.unquote(location))
        visited_results = utils.es_search('', activities=[], accessibilities=[])
        location_results = utils.es_search('', location=location, activities=[], accessibilities=[])
        context_dict = {"visited_results": visited_results, "location_results": location_results}
        return render(request, 'home/homepage.html', context=context_dict)

templates/home/base.html
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery-star.min.js'%}"></script>
    {% block script_block %}
    {% endblock %}
    <title>
        {% block title_block %}
        A VIEW FOR YOU
        {% endblock %}
    </title>
</head>

<body>
    <div>
        <div class="header">
            <div class="header-container">
                <div class='header-logo'>
                    <a id='header-title' href="{% url 'landscape:index' %}"><img src="{% static 'images/logo.jpeg' %}"
                            id="logo" alt="logo"> <span>A VIEW FOR YOU</span></a>
                </div>
                <div class='header-button'>

                    <a href="{% url 'auth:login' %}" class="btn btn-outline-primary">LOGIN/SIGNUP</a>

                </div>
            </div>
        </div>
        <div class='body-container'>
            {% block body_block %}
            {% endblock %}
        </div>

    </div>
</body>

</html>

templates/home/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block script_block %}
<link rel="stylesheet" href="{% static 'css/home.css'%}">
<script src = "{% static 'js/homepage.js'%}"></script>
{% endblock %}



{% block title_block %}
    {{ landscape.name }}
{% endblock %}

{% block body_block %}
<div style="border:2px solid grey;">
    <div style="background-image: url(/static/images/skyehome.png);background-size:100% 100%;padding: 7%; ">
    <div class="search-box">
        <div id='search-box-container'>
            <input type="text" class="form-control" id="query" placeholder = "Search for a view">
        </div>
        <div>
            <button id='search-button-search' class='btn btn-primary' value='SEARCH'>SEARCH</button>
        </div>
    </div>
</div>
</div>
  {% if visited_results|length > 0 %}
  <h4 class = 'gallery-heading'>Most Visited Landscapes</h4>
  <div id="visited-carousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner visited">
      {% for landscape in visited_results %}
      <div class="carousel-item">
        <div class="cards-wrapper">
        <div class="card landscape" value="{{landscape.slug}}">
          <div class = 'card-image-container'>
            <img src="{{landscape.image}}" class="card-img-top" alt="landscape-image">      
          </div>
          <div class="card-body">
            <h5 class="card-title">{{landscape.name}}</h5>
            <div class="rating"  value = '{{landscape.review.average_rating}}' style = 'display:inline; padding: 2px;'></div>
            <p class="card-text">{{landscape.review.count}} reviews<br> {{landscape.address}}</p>
          </div>
        </div>
      </div>
      </div>
      {% endfor %}
    </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#visited-carousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#visited-carousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
    </div>
    {% endif %}
    {% if location_results|length > 0 %}
    <h4 class = 'gallery-heading'>Landscapes near you</h4>
    <div id="location-carousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner location">
        {% for landscape in location_results %}
        <div class="carousel-item">
          <div class="cards-wrapper">
          <div class="card landscape" value = "{{landscape.slug}}">
            <div  class = 'card-image-container'>
              <img src="{{landscape.image}}" class="card-img-top" alt="landscape-image">    
            </div>
            <div class="card-body">
              <h5 class="card-title">{{landscape.name}}</h5>
              <div class="rating" id = 'location-{{landscape.id}}' value = '{{landscape.review.average_rating}}' style = 'display:inline; padding: 2px;'></div>
              <p class="card-text">{{landscape.review.count}} reviews<br> {{landscape.address}}</p>
            </div>
          </div>
        </div>
        </div>
        {% endfor %}
      </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#location-carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#location-carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
      </div>
      {% endif %}
{% endblock %}



   
        
        








    





 