a_view_for_you/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('auth/', include('authentication.urls')),
    path('landscape/', include('landscape.urls')),
] 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

landscape/urls.py
from django.urls import path
from landscape import views

app_name = 'landscape'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('<slug:landscape_name_slug>/', views.show_landscape, name='show_landscape'),
    path('<slug:landscape_name_slug>/add_review/', views.add_review, name='add_review'),
    path('<slug:landscape_name_slug>/like', views.add_like, name='add_like'),
]

landscape/models.py
from base64 import encode
from django.utils.timezone import now
from django.db import models
from django.core.validators import RegexValidator
from slugify import slugify
from authentication.models import User
from utils.utils import Base
from django.apps import apps


# Create your models here.
class Landscape(Base):
    name = models.CharField(max_length=apps.get_app_config('landscape').landscape_max_length, validators=[
        RegexValidator('^[A-Za-z0-9 ]+$')])
    description = models.TextField()
    address = models.TextField()
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='landscapes')
    activities = models.JSONField(default=list, blank=True)
    accessibilities = models.JSONField(default=list, blank=True)
    is_active = models.BooleanField(default=True)
    latitude = models.DecimalField(max_digits=10, decimal_places=6)
    longitude = models.DecimalField(max_digits=10, decimal_places=6)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Landscape, self).save(*args, **kwargs)


class Review(Base):
    TITLE_MAX_LENGTH = 500
    MULTIPLECHOICE_MAX_LENGTH = 500
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    description = models.TextField(blank=True)
    rating = models.FloatField(null=False, blank=True, default=5)
    visit_date = models.DateTimeField(default=now, blank=True)
    facilities = models.CharField(max_length=MULTIPLECHOICE_MAX_LENGTH)
    activities = models.CharField(max_length=MULTIPLECHOICE_MAX_LENGTH)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    landscape_id = models.ForeignKey(Landscape, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Photo(Base):
    review_id = models.ForeignKey(Review, on_delete=models.CASCADE, null=True)
    landscape_id = models.ForeignKey(Landscape, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='landscapes', null=True, blank=True)


class saved_landscapes(Base):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    landscape_id = models.ForeignKey(Landscape, on_delete=models.CASCADE, null=True)


class Like(Base):
    date = models.DateTimeField(default=now, blank=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    landscape_id = models.ForeignKey(Landscape, on_delete=models.CASCADE)

landscape/forms.py
import datetime
from email.policy import default
from unittest.util import _MAX_LENGTH
from django import forms
from landscape.models import Like, Review

ACTIVITIES = (
    ("boating", "Boating"),
    ("none", "None"),
    ("camping", "Camping"),
    ("fishing", "Fishing"),
    ("hiking", "Hiking"),
    ("swimming", "Swimming")
)

FACILITIES = (
    ("none", "None"),
    ("kids-area", "Kid's area"),
    ("parking", "Parking"),
    ("pet-friendly", "Pet friendly"),
    ("toilets", "Toilets"),
    ("wheelchair", "Wheelchair")
)


class ReviewForm(forms.ModelForm):
    title = forms.CharField(max_length=Review.TITLE_MAX_LENGTH, help_text="Title")
    description = forms.CharField(help_text="Description", required=False)
    rating = forms.IntegerField(help_text="Rating", initial=0)
    activities = forms.MultipleChoiceField(choices=ACTIVITIES, initial=['none'], required=False)
    facilities = forms.MultipleChoiceField(choices=FACILITIES, initial=['none'], required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Review
        fields = ('title', 'description', 'rating', 'visit_date', 'facilities', 'activities')


class LikeForm(forms.ModelForm):
    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Like
        fields = ('date',)

landscape/views.py
from django.shortcuts import redirect, render
from django.conf import settings
from django.http import Http404, JsonResponse
from django.apps import apps as django_apps
from django.views.decorators.csrf import csrf_exempt
from landscape.models import Landscape, Photo, Review, saved_landscapes
import json
from landscape.forms import ReviewForm
from landscape.models import Landscape, Photo, Review
from django.contrib.auth.decorators import login_required
from utils import utils


def index(request):
    context_dict = {}
    context_dict['activities'] = django_apps.get_app_config('landscape').activities
    context_dict['accessibilities'] = django_apps.get_app_config(
        'landscape').accessibilities
    if request.method == 'GET':
        if request.GET.get('q'):
            context_dict['q'] = request.GET.get('q')
        return render(request, 'landscape/index.html', context=context_dict)


def show_landscape(request, landscape_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        landscape = Landscape.objects.get(slug=landscape_name_slug)
        reviews = Review.objects.filter(
            landscape_id=landscape.id).order_by('-visit_date')[:5]
        photos = Photo.objects.filter(landscape_id=landscape.id)

        #for r in reviews:
        #    r.rating = utils.roundRating(r.rating)
        liked = False
        try:
            liked = True if saved_landscapes.objects.get(landscape_id=landscape, user_id=request.user) else False
        except:
            liked = False
        context_dict['reviews'] = reviews
        context_dict['landscape'] = landscape
        context_dict['photos'] = photos
        context_dict['liked'] = liked
        context_dict['url'] = Photo.objects.first().image.url
        return render(request, 'landscape/landscape.html', context=context_dict)
    except Landscape.DoesNotExist:
        return redirect('landscape:index')


@login_required()
def add_review(request, landscape_name_slug):
    try:
        landscape = Landscape.objects.get(slug=landscape_name_slug)
    except Landscape.DoesNotExist:
        landscape = None

    if landscape is None:
        return redirect('/landscape/')

    form = ReviewForm()
    error_message = None

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        images = request.FILES.getlist('images')

        if form.is_valid():
            review = form.save(commit=False)
            review.landscape_id = landscape
            review.user_id = request.user
            review.rating=float(request.POST['rating'])
            review.save()

            for image in images:
                Photo.objects.create(review_id=review, image=image, landscape_id=landscape)
            return redirect('landscape:index')
        print(form.errors)
        error_message = form.errors

    context_dict = {}
    context_dict['form'] = form
    context_dict['landscape'] = landscape
    context_dict['activities'] = django_apps.get_app_config('landscape').activities
    context_dict['accessibilities'] = django_apps.get_app_config(
        'landscape').accessibilities
    context_dict['error_message'] = error_message
    return render(request, 'landscape/add_review.html', context=context_dict)


def search(request):
    if request.method == 'GET':
        query = request.GET.get('q', '')
        location = {k: float(request.GET.get(k))
                    for k in ['lat', 'lon']} if request.GET.get('lat') else None
        # filters
        activities = request.GET.get('activities').split(',') if request.GET.get(
            'activities') and len(request.GET.get('activities').split(',')) > 0 else []
        accessibilities = request.GET.get('accessibilities').split(',') if request.GET.get(
            'accessibilities') and len(request.GET.get('accessibilities').split(',')) > 0 else []
        result = es_search(query, location=location, activities=activities, accessibilities=accessibilities)
        response = JsonResponse({"data": result, 'is_success': True})
        return response


def es_search(query='', **filters):
    # query
    es_query = {
        'bool': {
            'must': [
                {
                    'term': {
                        'is_active': True,
                    }
                }],
        }
    }
    if query:
        es_query['bool']['must'].append({
            'multi_match': {
                'fields': ['*'],
                'query': query,
                'fuzziness': 'AUTO'
            }
        })

    # location
    if 'location' in filters and filters['location']:
        es_query['bool']['must'].append({
            'geo_distance': {
                "distance": django_apps.get_app_config('landscape').GEO_DISTANCE,
                "location": filters['location'],
            }
        })

    additional_filters = len(filters['activities']) > 0 or len(filters['accessibilities']) > 0
    es_query['bool']['should'] = [] if additional_filters else None
    es_query['bool']['minimum_should_match'] = 1 if additional_filters else None

    # add the filter to the query if exists
    if len(filters['activities']) > 0:
        es_query['bool']['should'].append({
            'terms': {
                'activities': filters['activities'],
            }})

    if len(filters['accessibilities']) > 0:
        es_query['bool']['should'].append({
            'terms': {
                'accessibilities': filters['accessibilities'],
            }})
    es = django_apps.get_app_config('landscape').es
    ## sorting
    SORTING = [
        {'review.average_rating': {'order': 'desc'}},
        {'review.count': {'order': 'desc'}}
    ]
    result = es.search(index=settings.ES_INDEX,
                       query=es_query, sort=SORTING)
    result = [data['_source'] for data in result.body['hits']['hits']]
    return result


@login_required()
@csrf_exempt
def add_like(request, landscape_name_slug):
    try:
        landscape = Landscape.objects.get(slug=landscape_name_slug)
    except Landscape.DoesNotExist:
        return redirect('/landscape/')
    if request.method == 'PUT':
        data = json.loads(request.body)
        liked = data.get('liked', True)
        if liked:
            saved_landscapes.objects.update_or_create(landscape_id=landscape, user_id=request.user)
        else:
            saved_landscapes.objects.filter(user_id=request.user, landscape_id=landscape).delete()
        return JsonResponse({'data': {'message': 'like updated'}, 'is_success': True})
    else:
        raise Http404

templates/landscape/add_review.html
{% extends 'base.html' %}
{% load static %}

{% block script_block %}
    <link rel="stylesheet" href="{% static 'css/review.css' %}">
    <link rel="stylesheet" href="{% static 'css/rating.css' %}">
    <script src="{% static 'js/add_review.js' %}"></script>

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
            integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Jquery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
          integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
            integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

    <!-- Select picker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
{% endblock %}

{% block title_block %}
    Leave a review
{% endblock %}

{% block body_block %}
    <div class="landscapes-container">
        <h3>Leave a review</h3>

        <form enctype="multipart/form-data" id="page_form" method="post"
              action="{% url 'landscape:add_review' landscape.slug %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="rating">Your rating:</label><br>
                <div class="rating">
                    <input type="radio" name="rating" value="5" id="5"><label for="5">☆</label>
                    <input type="radio" name="rating" value="4" id="4"><label for="4">☆</label>
                    <input type="radio" name="rating" value="3" id="3"><label for="3">☆</label>
                    <input type="radio" name="rating" value="2" id="2"><label for="2">☆</label>
                    <input type="radio" name="rating" value="1" id="1"><label for="1">☆</label>
                </div>

                <div class="form-group">
                    <label for="visit_date">Date of visit:</label><br>

                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        <input id="visit_date" name="visit_date" type="text" class="form-control datetimepicker-input"
                               data-target="#datetimepicker1"/>
                        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label>Activities:</label><br>

                            <select class="selectpicker" multiple data-live-search="true" id="activities"
                                    name="activities">
                                {% for activity in activities %}
                                    <option value="{{ activity.name }}">{{ activity.display_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group column">
                            <label>Facilities:</label><br>

                            <select class="selectpicker" multiple data-live-search="true" id="facilities"
                                    name="facilities">
                                {% for accessibility in accessibilities %}
                                    <option value="{{ accessibility.name }}">{{ accessibility.display_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="title">Title of your review:</label><br>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="description">Your review:</label><br>
                    <textarea class="form-control" id="description" name="description"></textarea>
                </div>
                <div class="form-group">
                    <label for="images">Upload image</label>
                    <input name="images" id="images" type="file" accept="image/jpg, image/png, image/jpeg" multiple
                           class="form-control-file">
                </div>
                <button type="subimt" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <center>
    <span class='error-message'>
        {% if error_message %}
            {{ error_message }}
        {% endif %}
    </span>

    </center>
{% endblock %}

templates/landscape/index.html
{% extends 'base.html' %}
{% load static %}

{% block script_block %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <script>
        let q = "{{ q }}";
    </script>
    <script src="{% static 'js/search.js' %}"></script>
{% endblock %}

{% block body_block %}
    <div class="mb-2">
        <div class="search-container">
            <div class="collapse" id='search-container-filter-container'>
                <div class='search-container-filter'>
                    <h6>Activites</h6>
                    {% for activity in activities %}
                        <div class="form-check form-check-inline">
                            <input class="form-check-input activities" type="checkbox" value="{{ activity.name }}"
                                   id="flexCheckDefault">
                            <label class="form-check-label" for="flexCheckDefault">
                                {{ activity.display_name }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
                <div class='search-container-filter'>
                    <h6>Accessibilities</h6>
                    {% for access in accessibilities %}
                        <div class="form-check form-check-inline">
                            <input class="form-check-input accessibilities" type="checkbox" value="{{ access.name }}"
                                   id="flexCheckDefault">
                            <label class="form-check-label" for="inputlabel">
                                {{ access.display_name }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
            </div>


            <div class="search-box">
                <div id='search-box-container'>
                    <input type="text" class="form-control" id="query">
                </div>
                <div>
                    <button id='search-button-search' class='btn btn-primary' value='SEARCH'>SEARCH</button>
                </div>
            </div>

        </div>
        <div class="search-results">
        </div>
    </div>


    <ul>
        <!-- {% if landscapes %}
        {% for l in landscapes %}
            <li>
                <a href="{% url 'landscape:show_landscape' l.slug %}">{{ l.name }}</a>
            </li>
        {% endfor %}
    {% else %}
        <li><strong>There are no landscapes present.</strong></li>
    {% endif %} -->
    </ul>
{% endblock %}

templates/landscape/landscape.html
{% extends 'base.html' %}
{% load static %}

{% block script_block %}
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css"/>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" href="{% static 'css/jssocials-theme-flat.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/review.css' %}">
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/like.css' %}">
    <link rel="stylesheet" href="{% static 'css/landscape_detail_img.css' %}">
    <script src = "{% static 'js/homepage.js'%}"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
    <script src="{% static 'js/like.js' %}"></script>
    <script src="{% static 'js/jssocials.min.js' %}"></script>

{% endblock %}

{% block title_block %}
    {{ landscape.name }}
{% endblock %}

{% block body_block %}
    <div class="border-div"></div>
    <div class="address-container">
        <p class="address-text">{{ landscape.name }} , Address: {{ landscape.address }}</p>
        {% if '{{ landscape.is_active }} == True' %}
            <i>Open Now</i>
        {% else %}
            <i>Close</i>
        {% endif %}
        <div><span class="stars-container stars-{{ r.rating }}">★★★★★{{ r.rating }}</span></div>
    </div>
    <div class="landscapes-container">
        <div class="social-share"></div>

        {% if user.is_authenticated %}
            {% if liked %}
                <div class="heart-btn">
                    <div class="content heart-active">
                        <span class="heart heart-active"></span>
                        <span class="text heart-active">Like</span>
                    </div>
                </div>
            {% else %}
                <div class="heart-btn">
                    <div class="content">
                        <span class="heart"></span>
                        <span class="text">Like</span>
                    </div>
                </div>
            {% endif %}
        {% endif %}

    </div>

    {% if landscape %}
        <div class="landscape_img-box">
            <img src="{{ landscape.image.url }}" alt="">
        </div>


        <div class="information-box">
        <h2><strong>
            {{ landscape.name }}
        </strong>
        </h2>
        <p><i>{{ landscape.description }}</i></p>
        <p><i><strong>Address: {{ landscape.address }}</strong></i></p>
    {% endif %}

<div id="googleMap"></div>
<script>
    function myMap() {
        let mapProp = {
            center: new google.maps.LatLng("{{landscape.latitude}}", "{{landscape.longitude}}"),
            zoom: 17,
        };
        let map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
    }

</script>

<script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBWlVuiiEQ8z9SYTVhndKhwSI3HLGtuHp8&callback=myMap"></script>
</div>
    </div>
    <h3>Photo Gallery</h3>
    <!---CAROUSEL-->
    <ul class="slider">
        {% for p in photos %}
            <li>
                <img class="img-fluid" src="{{ p.image.url }}" alt="{{ p.review_id }}"/>
            </li>
        {% endfor %}

    </ul>
    <!--END CAROUSEL-->

    <h3>Recent reviews</h3>

    <a id='review-button' class="btn btn-primary" href="{% url 'landscape:add_review' landscape.slug %}"> Write a
        review</a>
    {% if reviews %}
        {% for r in reviews %}
            <div class='review-result-container block'>
                <div class='review-result-container-content'>
                    <p>
                        {{ r.user_id }} authored a review
                        <span class="right">
                    {{ r.visit_date }}
                </span>
                    </p>
                    <h4>{{ r.title }}</h4>
                    <div class="review_row">
                        <div class="review_column">
                            <div class="rating"  value = '{{r.rating}}' style = 'display:inline; padding: 2px;'></div>
                        </div>
                        <div class="review_column">
                            <p>{{ r.description }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <br/>
        {% endfor %}
    {% endif %}
    </div>
    </div>
{% endblock %}