a_view_for_you/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('auth/', include('authentication.urls')),
    path('landscape/', include('landscape.urls')),
] 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from .views import login, register, logout
from django.urls import path

app_name = 'auth'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout')
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.show_profile, name='profile'),
    path('edit/', views.edit_profile, name='edit'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-star.min.js' %}"></script>
    <script src="{% static 'js/lodash.min.js' %}"></script>
    <script src='https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js'></script>

    {% block script_block %}
    {% endblock %}
    <title>
        {% block title_block %}
            A VIEW FOR YOU
        {% endblock %}
    </title>
</head>

<body>
<div>
    <div class="header">
        <div class="header-container">
            <div class='header-logo'>
                <a id='header-title' href="{% url 'home:homepage' %}"><img src="{% static 'images/logo.jpeg' %}"
                                                                           id="logo" alt="logo"> <span><strong
                        style="font-size: 17px">A VIEW FOR
                                YOU</strong></span></a>
                <!-- <i style="margin-left: 10px">You will find your own landscape!</i> -->
            </div>
            <div class='header-container'>
                {% if request.path != '/auth/login/' %}
                    {% if user.is_authenticated %}
                        <div id='profile-image-container'>
                            <a href="{% url 'profile:profile' %}"><img id='profile-image'
                                                                       src="{{ user.image_url|default_if_none:'https://cdn3.vectorstock.com/i/1000x1000/34/52/user-icon-male-person-symbol-profile-avatar-sign-vector-19413452.jpg' }}"
                                                                       alt="{{ user.username }}'s profile image"
                                                                       width="38"></a>
                        </div>
                        <div class='header-button'>
                            <a href="{% url 'auth:logout' %}"
                               class="btn btn-outline-primary"><strong>LOGOUT</strong></a>
                        </div>
                    {% else %}
                        <div class='header-button'>
                            <a href="{% url 'auth:login' %}" class="btn btn-outline-primary">
                                <strong>LOGIN/SIGNUP</strong></a>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class='body-container'>
        {% block body_block %}
        {% endblock %}
    </div>

</div>
</body>

</html>